import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const now = new Date();
const daysAgo = (days: number) => new Date(now.getTime() - days * 24 * 60 * 60 * 1000);

export async function seed() {
  console.log("Seeding customer support refund database...");

  // Clean existing data
  await prisma.agentEvent.deleteMany();
  await prisma.agentSession.deleteMany();
  await prisma.refund.deleteMany();
  await prisma.order.deleteMany();
  await prisma.customer.deleteMany();

  // 15 realistic customer profiles with specific scenarios
  const customersData = [
    {
      id: "cust-uuid-001",
      customerId: "CUST-001",
      name: "Alice Smith",
      email: "alice.smith@example.com",
      phone: "+1-555-0101",
      order: {
        id: "ord-uuid-001",
        orderId: "ORD1001",
        productName: "Pro Audio Noise-Canceling Headphones",
        productCategory: "Electronics",
        amount: 120.0,
        currency: "USD",
        purchaseDate: daysAgo(10),
        deliveryDate: daysAgo(5),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-002",
      customerId: "CUST-002",
      name: "Bob Jones",
      email: "bob.jones@example.com",
      phone: "+1-555-0102",
      order: {
        id: "ord-uuid-002",
        orderId: "ORD1002",
        productName: "Italian Genuine Leather Wallet",
        productCategory: "Accessories",
        amount: 50.0,
        currency: "USD",
        purchaseDate: daysAgo(50),
        deliveryDate: daysAgo(45),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-003",
      customerId: "CUST-003",
      name: "Charlie Brown",
      email: "charlie.brown@example.com",
      phone: "+1-555-0103",
      order: {
        id: "ord-uuid-003",
        orderId: "ORD1003",
        productName: "Designer Winter Parka (Final Sale)",
        productCategory: "Apparel",
        amount: 200.0,
        currency: "USD",
        purchaseDate: daysAgo(15),
        deliveryDate: daysAgo(10),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: true,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-004",
      customerId: "CUST-004",
      name: "Diana Prince",
      email: "diana.prince@example.com",
      phone: "+1-555-0104",
      order: {
        id: "ord-uuid-004",
        orderId: "ORD1004",
        productName: "RGB Mechanical Gaming Keyboard",
        productCategory: "Electronics",
        amount: 150.0,
        currency: "USD",
        purchaseDate: daysAgo(20),
        deliveryDate: daysAgo(15),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
      hasRefund: true,
      refundData: {
        id: "ref-uuid-004",
        refundId: "REF1004",
        orderId: "ORD1004",
        customerId: "CUST-004",
        amount: 150.0,
        status: "APPROVED",
        reason: "Customer changed mind - previous successful refund",
        processedAt: daysAgo(14),
      },
    },
    {
      id: "cust-uuid-005",
      customerId: "CUST-005",
      name: "Evan Wright",
      email: "evan.wright@example.com",
      phone: "+1-555-0105",
      order: {
        id: "ord-uuid-005",
        orderId: "ORD1005",
        productName: "Artisanal Ceramic Coffee Press",
        productCategory: "Home & Kitchen",
        amount: 60.0,
        currency: "USD",
        purchaseDate: daysAgo(12),
        deliveryDate: daysAgo(8),
        status: "DELIVERED",
        condition: "DAMAGED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-006",
      customerId: "CUST-006",
      name: "Fiona Gallagher",
      email: "fiona.g@example.com",
      phone: "+1-555-0106",
      order: {
        id: "ord-uuid-006",
        orderId: "ORD1006",
        productName: "Ultra Fitness Smartwatch",
        productCategory: "Electronics",
        amount: 250.0,
        currency: "USD",
        purchaseDate: daysAgo(15),
        deliveryDate: daysAgo(10),
        status: "DELIVERED",
        condition: "USED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-007",
      customerId: "CUST-007",
      name: "George Harris",
      email: "george.h@example.com",
      phone: "+1-555-0107",
      order: {
        id: "ord-uuid-007",
        orderId: "ORD1007",
        productName: "Wireless Charging Pad",
        productCategory: "Electronics",
        amount: 35.0,
        currency: "USD",
        purchaseDate: daysAgo(8),
        deliveryDate: daysAgo(4),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-008",
      customerId: "CUST-008",
      name: "Hannah Abbott",
      email: "hannah.a@example.com",
      phone: "+1-555-0108",
      order: {
        id: "ord-uuid-008",
        orderId: "ORD1008",
        productName: "Ergonomic Mesh Office Chair",
        productCategory: "Furniture",
        amount: 350.0,
        currency: "USD",
        purchaseDate: daysAgo(3),
        deliveryDate: null,
        status: "PROCESSING",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-009",
      customerId: "CUST-009",
      name: "Ian Malcolm",
      email: "ian.m@example.com",
      phone: "+1-555-0109",
      order: {
        id: "ord-uuid-009",
        orderId: "ORD1009",
        productName: "Flagship 5G Smartphone",
        productCategory: "Electronics",
        amount: 999.0,
        currency: "USD",
        purchaseDate: daysAgo(10),
        deliveryDate: daysAgo(6),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: true,
      },
    },
    {
      id: "cust-uuid-010",
      customerId: "CUST-010",
      name: "Julia Roberts",
      email: "julia.r@example.com",
      phone: "+1-555-0110",
      order: {
        id: "ord-uuid-010",
        orderId: "ORD1010",
        productName: "Compact Portable Speaker",
        productCategory: "Electronics",
        amount: 80.0,
        currency: "USD",
        purchaseDate: daysAgo(14),
        deliveryDate: daysAgo(9),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-011",
      customerId: "CUST-011",
      name: "Kevin Bacon",
      email: "kevin.b@example.com",
      phone: "+1-555-0111",
      order: {
        id: "ord-uuid-011",
        orderId: "ORD1011",
        productName: "True Wireless Earbuds",
        productCategory: "Electronics",
        amount: 90.0,
        currency: "USD",
        purchaseDate: daysAgo(4),
        deliveryDate: daysAgo(2),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-012",
      customerId: "CUST-012",
      name: "Laura Croft",
      email: "laura.c@example.com",
      phone: "+1-555-0112",
      order: {
        id: "ord-uuid-012",
        orderId: "ORD1012",
        productName: "Clearance Trench Coat",
        productCategory: "Apparel",
        amount: 110.0,
        currency: "USD",
        purchaseDate: daysAgo(18),
        deliveryDate: daysAgo(12),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: true,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-013",
      customerId: "CUST-013",
      name: "Michael Scott",
      email: "michael.s@example.com",
      phone: "+1-555-0113",
      order: {
        id: "ord-uuid-013",
        orderId: "ORD1013",
        productName: "Handblown Crystal Glass Vase",
        productCategory: "Home Decor",
        amount: 75.0,
        currency: "USD",
        purchaseDate: daysAgo(26),
        deliveryDate: daysAgo(22),
        status: "DELIVERED",
        condition: "DAMAGED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
    {
      id: "cust-uuid-014",
      customerId: "CUST-014",
      name: "Nancy Drew",
      email: "nancy.d@example.com",
      phone: "+1-555-0114",
      order: {
        id: "ord-uuid-014",
        orderId: "ORD1014",
        productName: "HD Security Camera Pack",
        productCategory: "Home Electronics",
        amount: 180.0,
        currency: "USD",
        purchaseDate: daysAgo(20),
        deliveryDate: daysAgo(16),
        status: "DELIVERED",
        condition: "USED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
      hasRefund: true,
      refundData: {
        id: "ref-uuid-014",
        refundId: "REF1014-DENIED",
        orderId: "ORD1014",
        customerId: "CUST-014",
        amount: 180.0,
        status: "DENIED",
        reason: "Previous request denied due to used product condition",
        processedAt: daysAgo(15),
      },
    },
    {
      id: "cust-uuid-015",
      customerId: "CUST-015",
      name: "Oscar Martinez",
      email: "oscar.m@example.com",
      phone: "+1-555-0115",
      order: {
        id: "ord-uuid-015",
        orderId: "ORD1015",
        productName: "Stainless Steel Cookware Set",
        productCategory: "Kitchen",
        amount: 100.0,
        currency: "USD",
        purchaseDate: daysAgo(10),
        deliveryDate: daysAgo(7),
        status: "DELIVERED",
        condition: "UNUSED",
        finalSale: false,
        clearance: false,
        fraudFlag: false,
      },
    },
  ];

  for (const data of customersData) {
    const customer = await prisma.customer.create({
      data: {
        id: data.id,
        customerId: data.customerId,
        name: data.name,
        email: data.email,
        phone: data.phone,
      },
    });

    await prisma.order.create({
      data: {
        id: data.order.id,
        orderId: data.order.orderId,
        customerId: customer.customerId,
        productName: data.order.productName,
        productCategory: data.order.productCategory,
        amount: data.order.amount,
        currency: data.order.currency,
        purchaseDate: data.order.purchaseDate,
        deliveryDate: data.order.deliveryDate,
        status: data.order.status,
        condition: data.order.condition,
        finalSale: data.order.finalSale,
        clearance: data.order.clearance,
        fraudFlag: data.order.fraudFlag,
      },
    });

    if (data.hasRefund && data.refundData) {
      await prisma.refund.create({
        data: {
          id: data.refundData.id,
          refundId: data.refundData.refundId,
          orderId: data.refundData.orderId,
          customerId: customer.customerId,
          amount: data.refundData.amount,
          status: data.refundData.status,
          reason: data.refundData.reason,
          processedAt: data.refundData.processedAt,
        },
      });
    }
  }

  console.log("Database seeded successfully with 15 customers, orders, and refund records.");
}

if (require.main === module) {
  seed()
    .catch((e) => {
      console.error(e);
      process.exit(1);
    })
    .finally(async () => {
      await prisma.$disconnect();
    });
}
